# Generated by Django 6.0.3 on 2026-04-25 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('age_min_mois', models.IntegerField()),
                ('age_max_mois', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('obligatoire', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['age_min_mois'],
            },
        ),
    ]
