# Generated by Django 6.0.3 on 2026-04-25 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conseils', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccin',
            name='age_affichage',
            field=models.CharField(default='Naissance', max_length=50),
            preserve_default=False,
        ),
    ]
