# Generated by Django 6.0.3 on 2026-04-26 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conseils', '0002_vaccin_age_affichage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConseilNutritionnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('categorie', models.CharField(choices=[('aliment', "Type d'aliment"), ('probleme', 'Problème de santé')], max_length=20)),
                ('age_min_mois', models.IntegerField(help_text='Âge minimum en mois')),
                ('age_max_mois', models.IntegerField(help_text='Âge maximum en mois')),
                ('mots_cles', models.CharField(blank=True, help_text='Ex: diarrhée, fièvre, protéines', max_length=200)),
            ],
            options={
                'ordering': ['age_min_mois'],
            },
        ),
    ]
