# Generated by Django 6.0.3 on 2026-05-09 23:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_parent_options_alter_parent_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='date_inscription',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parent',
            name='nom',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='parent',
            name='prenom',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='parent',
            name='ville',
            field=models.CharField(blank=True, default='Cotonou', max_length=100),
        ),
        migrations.AlterField(
            model_name='parent',
            name='quartier',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
