# Generated by Django 6.0.3 on 2026-05-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_parent_date_inscription_parent_nom_parent_prenom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
