# Generated by Django 6.0.3 on 2026-04-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('type_etab', models.CharField(choices=[('centre', 'Centre de Santé'), ('pharmacie', 'Pharmacie')], max_length=20)),
                ('adresse', models.CharField(max_length=300)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('telephone', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
