# Generated by Django 5.2.17 on 2026-09-28 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sante', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etablissement',
            options={'ordering': ['nom']},
        ),
        migrations.AddField(
            model_name='etablissement',
            name='commune',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='fait_vaccination',
            field=models.BooleanField(default=False, help_text='Le centre organise des séances de vaccination du PEV.', verbose_name='Propose la vaccination PEV'),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='horaire_vaccination',
            field=models.CharField(blank=True, help_text='Ex. « 08h00 - 12h00 ».', max_length=100, verbose_name='Horaire des séances'),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='jours_vaccination',
            field=models.CharField(blank=True, help_text='Codes séparés par des virgules, ex. « lundi,mercredi ».', max_length=80, verbose_name='Jours de vaccination'),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='maj_vaccination',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='precision_vaccination',
            field=models.CharField(blank=True, help_text='Ex. « Séance de rattrapage le dernier samedi du mois ».', max_length=250, verbose_name='Précision'),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='source_vaccination',
            field=models.CharField(blank=True, choices=[('', 'Non renseigné'), ('centre', 'Déclaré par le centre'), ('osm', 'OpenStreetMap'), ('admin', 'Saisi par l’administration')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='type_etab',
            field=models.CharField(choices=[('centre', 'Centre de Santé'), ('pharmacie', 'Pharmacie'), ('hopital', 'Hôpital'), ('hopital_zone', 'Hôpital de zone'), ('clinique', 'Clinique')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='etablissement',
            index=models.Index(fields=['fait_vaccination'], name='sante_etabl_fait_va_279f84_idx'),
        ),
        migrations.AddIndex(
            model_name='etablissement',
            index=models.Index(fields=['type_etab'], name='sante_etabl_type_et_11c259_idx'),
        ),
    ]
