# Generated by Django 5.2.8 on 2026-10-03 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sante', '0003_marquer_centres_vaccinateurs'),
    ]

    operations = [
        migrations.AddField(
            model_name='etablissement',
            name='jours_confirmes',
            field=models.BooleanField(default=False, verbose_name='Jours confirmés'),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='jours_vaccination_9mois',
            field=models.CharField(blank=True, max_length=80, verbose_name='Jours dédiés aux 9 mois'),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='fait_vaccination',
            field=models.BooleanField(default=False, verbose_name='Propose la vaccination PEV'),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='horaire_vaccination',
            field=models.CharField(blank=True, max_length=100, verbose_name='Horaires des séances'),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='jours_vaccination',
            field=models.CharField(blank=True, max_length=80, verbose_name='Jours de vaccination'),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='precision_vaccination',
            field=models.CharField(blank=True, max_length=250, verbose_name='Précision'),
        ),
    ]
