# Generated by Django 6.0.3 on 2026-04-25 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_parent_options_alter_parent_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enfant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.parent')),
            ],
        ),
        migrations.CreateModel(
            name='MesureEnfant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_mesure', models.DateField(auto_now_add=True)),
                ('poids', models.FloatField(help_text='Poids en kg')),
                ('taille', models.FloatField(help_text='Taille en cm')),
                ('muac', models.FloatField(blank=True, help_text='Périmètre brachial en cm', null=True)),
                ('enfant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enfants.enfant')),
            ],
        ),
    ]
