# Generated by Django 6.0.3 on 2026-05-02 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enfants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enfant',
            options={'ordering': ['date_naissance']},
        ),
        migrations.AddField(
            model_name='enfant',
            name='prenom',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='VaccinRecu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_vaccin', models.CharField(max_length=100)),
                ('date_reelle', models.DateField()),
                ('remarque', models.TextField(blank=True)),
                ('enfant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccins_recus', to='enfants.enfant')),
            ],
            options={
                'ordering': ['date_reelle'],
            },
        ),
    ]
