# Generated by Django 5.2.17 on 2026-09-28 23:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sante', '0002_alter_etablissement_options_etablissement_commune_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionnelSante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fonction', models.CharField(choices=[('infirmier', "Infirmier(ère) diplômé(e) d'État"), ('sage_femme', 'Sage-femme'), ('medecin', 'Médecin'), ('agent_pev', 'Agent PEV / vaccinateur'), ('aide_soignant', 'Aide-soignant(e)'), ('autre', 'Autre personnel de santé')], max_length=20)),
                ('structure_libre', models.CharField(blank=True, max_length=200, verbose_name='Structure (si absente de la liste)')),
                ('numero_ordre', models.CharField(blank=True, max_length=50, verbose_name="Numéro d'ordre ou matricule")),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de validation'), ('valide', 'Validé'), ('refuse', 'Refusé')], default='en_attente', max_length=12)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('etablissement', models.ForeignKey(blank=True, help_text="Formation sanitaire dont l'agent est responsable.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professionnels', to='sante.etablissement')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professionnel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Professionnel de santé',
                'verbose_name_plural': 'Professionnels de santé',
                'ordering': ['-date_demande'],
            },
        ),
    ]
